### ISSUE TITLE
fulllines, twolines, morethantwolines

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#264]
Hey,

thank you very much for the new feature! It's very useful!

I do have one point for the wishlist, though: For the sake of accuracy, some people do not like the \morethantwolines variant, while they appreciate the \twolines one. Would there be any chance to have "p. 7sq" for "p. 7–8", but at the same time "p. 7–9" and not "p. 7sqq"?

Maybe by leaving \morethantwolines empty (as opposed to the current setting to use \twolines then)?

(BTW: Another, more complicated wishlist item is coming up.)

**Comment by maieul** [comment]
yes, I have thought to this problem today, and was anxious about where people will ask for it.

It could not be with  \morethantwolines empty, because, now, it is used for people who wants to have the same thing for  \morethantwolines and \twolines (for example, in french we use p. but not pp. and I think it is the same). And I don't want to break compatibility. I was thinking to something like "twolinesbutnotemore" toggle. 

It should be easy to add, but I am not sur about the gook command name

**Comment by baem2** [comment]
You might want to think about adding it as a global option for the package:

linenumbers=numbersonly (now fulllines) or sequens (twolines) or sequenter (two and more)

(biblatex calls the strings "sequens" for sq and "sequenter" for sqq.)

**Comment by maieul** [comment]
no, no global option. Biblatex works with global option, but not eledmac. It works with local command. I don't want to make an exception for linenumber and not for other.

Global options for eledmac are very short and concerns things related with the loading of the package. That is not the case here.

Keep coherence.

**Comment by baem2** [comment]
Oh I didn't know that and I totally see your point. Another way would be a command similar to \footparagraph{} \foottwocol{} \footthreecol{}

Or as optional option for the footnote command as it is now, that's just fine.

No matter how you do it: Thanks for all your hard work!

**Comment by maieul** [comment]
sorry? I don't understand your "other way"

**Comment by maieul** [comment]
I was thinking just a basic command \twolinesbutnotmore[series][true/false] as all the toggle hooks command defined in paragraph "Display options" (was 4.4, now 5.4) of the handbook...

**Comment by baem2** [comment]
Yes, that's similar to what I mean. I referred to what is 5.3 in the current manual.

Two things to think about, though: Does it make sense to have the "series" part? I mean, most people probably would like to have it the same for all notes. But if it is not that much work, you can add the series option anyway ...

And secondly, it probably is better to have it this way: Say the default option is always "sq and sqq". Then the users should have the choice to have a) "sq, but not sqq" and b) "neither sq nor sqq". So maybe a true/false is not what we need, but instead something like

\linenumbersfromto{series}{option}

where "option" could be something like "alwaysnumbers", "sq", "sqq" or something like that.

As you provide that option currently, it should then maybe still be possible to overwrite it with the optional argument of the footnote command ...?

**Comment by maieul** [comment]
the series part is a general way for such command. It's better and simpler to have a option used but noone than to have not and to need to add it later. 

All the 5.3 are by series, because all are declared with  the same command (\newhookcommand@series or  \newhookcommand@series@reload or \newhooktoggle@series depending of some specificity). And there is no reason to make exception for it. Especially, for this case, there is a relation with #254 which allow use to be. 

The option way is more expansive, and will need more test and will ask question about syntaxe.

for exemple how could I explain that I want f. and ff. ? Now, the toggle way is the best.

**Comment by baem2** [comment]
Okay, the toggle version will be all fine. Thanks a lot! :)

**Comment by maieul** [comment]
in general i try to have more binary command : option set or not, texte defined or not.
>

**Comment by maieul** [comment]
please try branch issue264, which adds \twolinesbutnotmore

**Comment by maieul** [comment]
There was a bug. now, should be ok.

**Comment by baem2** [comment]
It is working as expected. Thank you very much, that's really great!

**Comment by maieul** [comment]
ok, will be released soon
