### ISSUE TITLE
Eledmac incompatible with footmisc

### ISSUE THREAD

**Issue by wangjunqi** [maieul/ledmac#278]
For some reason, I have to use footmisc together with eledmac.
Here is my example,

\documentclass{book}
\usepackage{eledmac}
\usepackage[para,perpage]{footmisc}
\firstlinenum{1}
\linenumincrement{1}
\begin{document}
\beginnumbering
\pstart
LaTeX is a high-quality open source typesetting software that produces professional prints and PDF files. However, as LaTeX\footnote{What a wonderfull tool} is a powerful and complex tool, getting started can be intimidating. There is no official support and certain aspects such as layout modifications can seem rather complicated. It may seem more straightforward to use Word or other WYSIWG programs, but once you've become acquainted, LaTeX's capabilities far outweigh any initial difficulties. This book guides you through these challenges and makes beginning with LaTeX easy. If you are writing mathematical, scientific, or business papers, then this is the perfect book\footnote{e-book} for you.
\pend
\pstart
\edtext{LaTeX Beginner's Guide}{\Afootnote{A test for Afootnote}} offers you a practical introduction to LaTeX. Beginning with the installation and basic usage, you will learn to typeset documents containing tables, figures, formulas, and common book \edtext{elements}{\Afootnote{A test}} like bibliographies, glossaries, and indexes. Lots of step-by-step examples start with fine-tuning text, formulas and page layout and go on to managing complex documents and using modern PDF features. It's easy to use LaTeX, when you have LaTeX Beginner's Guide at hand.
\pend
\endnumbering
\end{document}

After several tests, I realized that If I stop using  linenumbers of eledmac, or option para of footmisc package, there will be no conflict. But if these two are used at the same time, Latex warns me command \makecol has changed and the result is as follows:
![1](https://cloud.githubusercontent.com/assets/8775005/7100349/2a47fd9e-e058-11e4-906c-2d98d4782812.PNG)

I tried my best to settle down this problem. But I failed. If you have some time, please help me to solve this problem. I really appreciate your help.

**Comment by maieul** [comment]
why do you need footmisc ? eledmac as its own system of footnote, very complete.

the equivalent of option para of footmisc is \footparagraph

**Comment by wangjunqi** [comment]
Thank you for your reply.
Because I want to use this command.
\newcommand{\footnotepair}[2]{%
\footnotemark #1\footnotemark[\value{footnote}]\footnotetext{#2}%
%}
Through this, I can add superscripts both before and after a piece of text. If possible, would you like to teach me how to achieve this goal through eledmac?
And I've carefully read the Introduction of Eledmac and found \footparagraph, but still do not know how to use  this command. Do I need to input \footparagraph{A} in preamble to set all foonotes in footnoteA in one paragraph?

**Comment by wangjunqi** [comment]
Thank you so much for your kindness and help. Example #278 is exactly what I want.

**Comment by maieul** [comment]
Hum, there is quite confusion in your question and example. 

First, you shoud know that there is TWO types of footnotes:
- critical footnotes which are the "raison d'être" of eledmac. Such notes are called with this syntax:
`\edtext{lemma}{\Afootnote{text}}`. Such notes don't use footnote mark, but line number.
- familiar footnotes, which are similar to the `\footnote{xxx}` of LaTeX, but, are `\footnoteA` `\footnoteB` `\footnoteC` etc.

For each type of notes there is six series (by default) : A, B, C, D, E, Z.

In your case, you need familiar footnotes. Commands which changes the setting of familiar footnotes has a X at the end. Commands which changes the setting of critical footnotes has no X, or X at the begin.

So `\footparagraph{A}` is for the critical footnotes of the series A, while `\footparagraphX` is for familiar footnotes of the series A.

You have a second problem, which is to have footnotemark before and after an element. The best solution is to call the footnote before the element, and to insert the footnote mark twice after the element. The footnotemark of the series A can be call with `\@footnotemarkA` (I am not sur this point is clear in the handbook, indeed, because normally people have not to call it manually).

So

`````
\makeatletter
\newcommand{\footnotepair}[2]{%
  \footnoteA{#2}#1%
  \@footnotemarkA%  
}
\makeatother
\footparagraphX{A}
`````
And the full MWE 

https://github.com/maieul/ledmac/blob/93ba6d576b0677c6e63274ab5071c5d436638b80/issue278.tex

**Comment by wangjunqi** [comment]
After seeing your example and explanation, I have a much better understanding of eledmac and what I need to do in my job. Thank you very much.
