### ISSUE TITLE
pb de numerotation de titre parallel en columns

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#391]
\documentclass{article}

\usepackage[series={},noend,nocritical,nofamiliar]{reledmac}
\usepackage{reledpar}
\begin{document}
\begin{pairs}
\begin{Leftside}
\beginnumbering
\pstart[\section{toto}]
s
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart[\section{toto}]
s
\pend
\endnumbering
\end{Rightside}
\end{pairs}
\Columns
\begin{pages}
\begin{Leftside}
\beginnumbering
\pstart[\section{toto}]
s
\pend
\endnumbering
\end{Leftside}
\begin{Rightside}
\beginnumbering
\pstart[\section{toto}]
s
\pend
\endnumbering
\end{Rightside}
\end{pages}
\Pages
\end{document}

**Comment by Tim-at-AST** [comment]
Unfortunately, because I am a newbie, I have not been able to test this.  I use Text Live (mac) and am not familiar enough with overwriting a particular package.  However, I have tested your example on the ordinary package and this is definitely the correct problem.  I have opened another issue about Arabic.

**Comment by maieul** [comment]
the explanation are here https://github.com/maieul/ledmac#debug-and-feature-requests

**Comment by maieul** [comment]
ok, I close this issue. The new version is working (cf screenshot). It will be released in next version of reledmac/reledpar.
![capture d ecran 2015-09-02 a 12 33 17](https://cloud.githubusercontent.com/assets/636640/9628891/ed62e30c-516e-11e5-84c6-d0f496cf20ff.png)
