### ISSUE TITLE
Huge vertical space between first and second line of a critical note

### ISSUE THREAD

**Issue by GiulioGx** [maieul/ledmac#544]
Hi, I don't know exactly what is causing this strange behavior. I have some long critical notes that span 2 lines and very often several blank lines are added between the first and the second line of the note.

I am writing a critical edition with Latin and Italian on facing pages.  My chunks are composed like this for the Latin part

`\begin{astanza}
			Tyrrheni, procul hinc, procul \edtext{hinc}{\Afootnote{hic P}} estote, labores;&
			Ocia securus garrula Bacchus amat.&
			Dic, puer, anne aliquos \edtext{quereris}{\Afootnote{queris P}} malesanus amores?&
			\edtext{Num tua sollicitet pectora hetruscus amor}{\Cfootnote{Ovid. \textit{Am}. 1, 2, 5}}?&
			Margara num, \edtext{roseove decens Grecinna colore}{\Cfootnote{Hor. \textit{Carm}. 2, 4, 3; Prop. 2, 25, 41-42}}?&
			Num facie et blandis grata Terinna iocis?\&
\end{astanza}`

and like this for the Italian:

`\pstart
	    Via da qui, italiche imprese, restate lontane da qui; Bacco senza pensieri gradisce gli ozi loquaci. Pazzerello d’un ragazzo, forse stai soffrendo per qualche amore? Un’etrusca passione forse inquieta il tuo cuore? Di Margherita si tratta o dell’elegante Grecinna col suo roseo colore? Forse è Terinna per il suo faccino gradita e per i trastulli d’incanto? 
\pend`

I am using `\advancedshiftedpstarts`.

Thanks for your work!

**Comment by maieul** [comment]
please provide a FULL MWE. I can't work with your example.

**Comment by GiulioGx** [comment]
Thank you for your immediate reply. I've put together a mwe. Thanks!
[mwe.zip](https://github.com/maieul/ledmac/files/310218/mwe.zip)

**Comment by maieul** [comment]
thanks. As you can see with the MWE, the problem is with \Xonlyside. So next time, send directly the mwe

**Comment by maieul** [comment]
ps "\skipnumbering\eledsection{Al contadino }" is a no sens.
\eledsection is precisly to get line number. If you want section without number, use simply optional argument of \pstart

**Comment by maieul** [comment]
found the problem. Will do the correction tomorrow

**Comment by GiulioGx** [comment]
Thanks a lot (also for you other observations)! ;)

**Comment by maieul** [comment]
please try branch issue544

**Comment by GiulioGx** [comment]
That works! I've tried it also on the complete book and it looks good. Again, thanks a lot!

**Comment by maieul** [comment]
your'e welcome.

this version will be published soon on CTAN

**Comment by GiulioGx** [comment]
Hey, I am sorry I didn't notice it sooner but although notes are now fine the synchronization seems to be broken. I attach a fairly more long example where the problem should be evident. (Look, for example, at how the first Latin stanza is broken in two without reason, I think).

I hope I am not doing something wrong ;). Thanks!
[new_mwe.zip](https://github.com/maieul/ledmac/files/314442/new_mwe.zip)

**Comment by maieul** [comment]
indeed, it seems there is a problem to get stable numbering�

**Comment by maieul** [comment]
OK. I have thought a lot and make many test. And my conclusion is that you use `Xonlyside` in a way that is not conceveid for. 

I explain you: Xonlyside is supposed to be for note called in the same size that have to been printed. So if you tel `\Xonlyside[A]{R}`, your note must called in right side. It just avoid long note to continue on the left side.

Using as you do make reledpar not able to get stable state of the page, because every time reledpar make left page shorter to be aligned with right page, the number of notes on the right page is decreased… and so in the next run, we need re-alignement etc. etc.

For now, the only way to do what you want is to use `\xxref` and `\lemma` mechanism to call the footnote on the right side but refering to line / content of the left side. 

I think there could be a way create generic command to do that. For example the syntax would be `\edtextlater{...}{footnotecommande}` called on the leftside `\edtextnow` called on the right side.

But this a complex implement…
