### ISSUE TITLE
Subline numbers in the apparatus of manuscripts with \msdata

### ISSUE THREAD

**Issue by davidesimo** [maieul/ledmac#859]
# Version
reledmac 2020/02/04 v2.32.4
reledpar 2019/11/04 v2.22.4

# TeX Engine
LuaLaTeX

# Description
If I use \msdata to mark sections of text where sublineation is on, the apparatus of manuscripts does not show subline numbers. The same happens with parallel typesetting.

# Minimal Working Example
```latex
% !TEX encoding = utf8
% !TEX TS-program = lualatex
% !TEX spellcheck = it_IT

\documentclass{book}

\usepackage{fontspec}
\setmainfont{Junicode}
\usepackage{polyglossia}
\setmainlanguage{italian}

\usepackage[series={A},noend,nofamiliar,noledgroup,nopbinverse]{reledmac}
\firstlinenum{1}
\linenumincrement{1}
\firstsublinenum{1}
\sublinenumincrement{1}
\Xsublinesep{}
\sublinenumberstyle{alph}

\begin{document}

\beginnumbering

\setstanzaindents{0,0}
\setcounter{stanzaindentsrepetition}{1}
\begin{stanza}
    \msdata{ABCDEF}Primo verso&
    Secondo verso&
    Terzo verso\stopmsdata&
    \startsub\msdata{EF}\emph{Primo verso interpolato}&
    \emph{Secondo verso interpolato}\stopmsdata\endsub&
    \msdata{ABCDEF}Quarto verso&
    Quinto verso&
    Sesto verso\stopmsdata\&
\end{stanza}

\endnumbering

\end{document}
```

**Comment by maieul** [comment]
Please try branch issue 859.

Also, you should add \null before your \startsub, to be sur some content (null) content is typeset, and so have a correct line number also if you use  `\setstanzaindents{1,0}`

**Comment by davidesimo** [comment]
Thank you! I tried and it works.

I don’t understand the thing about \null: if I change \setstanzaindents{0,0} to {1,0} the line numbers are wrong (4 and 4a instead of 3a and 3b) and the same happens if I add \null before \startsub.

**Comment by maieul** [comment]
sorry, I tried many things, and my spirit was quite confused. 
So
in your case "Primo verso interpolato" and "Secondo verso interpolato" must have the same linenumber that "Terzo verso". 

But if you type `\startsub Primo verso interpolato`, the verse have already started when `\startsub`.
So, the sublineation start at the end of `Secondo verso interpolato` and you get 4 / 4a instead of 3a/3b.


The only exception is, when the the fist argument of `setstanzaindents` is equal to one (your case). 
It is indeed  a bug of reledmac.  In your case, you get the good result, but it is accidently. The handbook say 

> When sub-lineation is in effect, the line number counter is frozen and the sub-line
> counter advances instead. If one of these commands appears in the middle of a line,
> it doesn’t take effect until the next line; in other words, a line is counted as a line or
> sub-line depending on what it started out as, even if it changes in the middle.
> 

Consequently, you should use `\startsub` at the very end of the previous line. In this case, you won't be dependant of the value of the first argument of \stestanzaindent.  It is also, conceptually, more efficient.

Cf  8f70f53a for an example of what you should do.

(I don't know if I will correct this bug, as the correction could have boarder effect)

**Comment by maieul** [comment]
Sorry, b0cf2ac7 for example

**Comment by maieul** [comment]
I have answer on SE. Please valide and vote up to the answer.

**Comment by davidesimo** [comment]
Thank you, I had overlooked that passage of the handbook.
