### ISSUE TITLE
reledmac error: \pstart in \edtext first argument.

### ISSUE THREAD

**Issue by maras** [maieul/ledmac#874]
Hello.

First of all I want to thank you for the maintenance of this wonderful package. 

Recently I experienced this error while about two years ago (or erlier) the same document compiled fine. 

# Version
reledmac 2020/05/31 v2.33.0 Manjaro Linux

# TeX Engine
I am using pdfLaTeX in Lyx.

# Regression
I wasn't using reledmac about two years or even more, so I can't say when this behaviour appeared. Maybe it is related to this change: 

> v2.32.7. Fix bug with \lineation{pstart} and \edtext in the very first line of a \pstart

# Description
Document from MWE not compiles both in Lyx and pure LaTeX. Problem occurs in parallel and normal typesetting. Error: 

>./reledmac.tex:13: Package reledmac Error: \pstart in \edtext first argument.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{reledmac}
\lineation{pstart}

\begin{document}
\beginnumbering

\pstart

\edtext{some text
\pend
\pstart
some text}{\lemma{some \dots\ text}\Afootnote{\emph{some text}}}
\pend

\endnumbering
\end{document}
```

# Workaround

This problem disappears when edtext encompass only one paragraph:
```latex
\documentclass{article}
\usepackage{reledmac}
\lineation{pstart}

\begin{document}
\beginnumbering

\pstart

\edtext{some text}{\lemma{some \dots\ text}\Afootnote{\emph{some text}}}
\pend
\pstart
some text
\pend

\endnumbering
\end{document}
```

**Comment by maieul** [comment]
Well,

that is not a bug, not directly. As the message explain, you SHOULD NOT use `\pstart` inside an `\edtext` argument. Maybe you document worked well in the past, but that is because you were lucky. There may have many side effect with advanced feature of reledmac. That is why I added this warning. 

So, just split your edtext in two. You may use `\lemma` and `\xxref`  tools  to get the good linenumber in the apparatus.
