### ISSUE TITLE
\ledleftnote needs %

### ISSUE THREAD

**Issue by michael2457** [maieul/ledmac#895]
# Version  2020/12/20 v2.35.1

# TeX Engine
XeLaTeX  (didn't try another engine)

# Regression

# Description

 I have not tried parallel typesetting.

In a numbered stanza, \ledleftnote forces the line of verse text a little to the right.  If I add % immediately after the argument of the commant, the text is correctly aligned.  This may not be a bug, since LaTeX sometimes requires this (for reasons and circumstances I don't fully understand), but I thought you should judge whether to treat it as a bug.

# Minimal Working Example

```latex
\documentclass{article}
\usepackage{reledmac}
 \setstanzaindents{0,0}
 \setcounter{stanzaindentsrepetition}{1} 
 \firstlinenum{4}
 \linenumincrement{4}

\usepackage{fontspec}

\begin{document}

\beginnumbering
\stanza
\ledleftnote{Strophe:}
We make more fuss of ballads than of blueprints ---&
That's why so many poets end up rich,&
While engineers scrape by in cheerless garrets.&
Who needs a bridge or dam? Who needs a ditch?\&
\vspace{1ex}
\stanza
\ledleftnote{Antistrophe:}%
We make more fuss of ballads than of blueprints ---&
That's why so many poets end up rich,&
While engineers scrape by in cheerless garrets.&
Who needs a bridge or dam? Who needs a ditch?\&

\endnumbering
  
\end{document}
```

# Workaround
The first \ledleftnote command has a carriage return immediately after the argument, and the line of verse is not aligned with the other ones in the stanza.
Notice that the second \ledleftnote command has a % immediately after the argument, and that the verse line is aligned correctly.

Thanks for your attention to this, if it is considered a problem.  And thanks very, very much for this package!
-Michael Blaustein

**Comment by maieul** [comment]
Well, that is not a bug, but a classical feature of TeX. It is because, when you don't use a `%`, a  line break means a space. There is a features inside `\stanza` which gobble the following space. But if you insert any macro between, than make something like `\stanza<a gobble space>\macro<a non gobble space>`. I could of course add gobbling at the end of `\leftsidenote`, but that could break some case where the space are required. 

Another solution for you is to do 
```
\stanza
\ledleftnote{Antistrophe:}We
```
